### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by oliver-sanders** [Tinche/aiofiles#100]
At the moment PyPi doesn't think `aiofiles` supports Python3.9 - https://pypi.org/project/aiofiles/

And conda-forge doesn't provide a Python3.9 build - https://anaconda.org/conda-forge/aiofiles/files

(I think conda-forge will auto create a rebuild for Python3.9 when a new PyPi release is made with 3.9 metadata)

**Comment by yeraydiazdiaz** [comment]
> At the moment PyPi doesn't think aiofiles supports Python3.9 - https://pypi.org/project/aiofiles/

Looks like it does now? I can certainly install it on 3.9.

Conda now lists a [source distribution for 0.7.0](https://anaconda.org/conda-forge/aiofiles/files?version=0.7.0), maybe that solved the issue?

**Comment by oliver-sanders** [comment]
Pip metadata is now correct and we have a noarch package on conda forge, all good.
