### ISSUE TITLE
Pypi calls aiofiles license "Other/Proprietary (Apache 2.0)"

### ISSUE THREAD

**Issue by vegai** [Tinche/aiofiles#103]
https://pypi.org/project/aiofiles/

Also this makes some automatic license checker tools fail on aiofiles. We started seeing this when upgrading to 0.7.0.

**Comment by vegai** [comment]
https://python-poetry.org/docs/pyproject/#license recommends calling the license `Apache-2.0`, currently it's `Apache 2.0` in pyproject.toml.

**Comment by atugushev** [comment]
FTR it's still "Other/Proprietary (Apache 2.0)" on PyPI
![image](https://user-images.githubusercontent.com/7377671/136816870-50ed39e4-92ea-4cd0-81d4-fc7c24efa092.png)
