### ISSUE TITLE
Incorrect license type in package metadata

### ISSUE THREAD

**Issue by claws** [Tinche/aiofiles#106]
I have a CI step which checks for acceptable licences. Aiofiles seems to have recently (not exactly sure when) changed its reported licence from Apache 2 to Other/Proprietary. This can be seen on the aiofiles PyPI page. 

Apache 2 is listed in the ``pyproject.toml`` file which seems correct but perhaps there is some issue in matching an expected field name or certain licence type that results in a different licence being found by PyPI and my CI licence checking step .

**Comment by Tinche** [comment]
Fixed recently: https://github.com/Tinche/aiofiles/commit/3a66417d89e204aa7fa424b39b858126412e4d3c

I guess I need to re-release since it's breaking people :)
