### ISSUE TITLE
AIOFiles Take Longer Than Normal File Operation

### ISSUE THREAD

**Issue by SinaMobasheri** [Tinche/aiofiles#110]
*hi developers*
*I have a question I'm new to the python async world and I write some code to test the power of `asyncio`, I create 10 files with random content, named `file1.txt, file2.txt, ..., file10.txt`*

***here is my code:***
```python
import asyncio
import aiofiles
import time

async def reader(pack, address):
    async with aiofiles.open(address) as file:
        pack.append(await file.read())

async def main():
    content = []
    await asyncio.gather(*(reader(content, f'./file{_+1}.txt') for _ in range(10)))

    return content

def core():
    content = []
    for number in range(10):
        with open(f'./file{number+1}.txt') as file:
            content.append(file.read())
    
    return content

if __name__ == '__main__':
    # Asynchronous
    s = time.perf_counter()
    content = asyncio.run(main())
    e = time.perf_counter()
    print(f'Take {e - s: .3f}')

    # Synchronous
    s = time.perf_counter()
    content = core()
    e = time.perf_counter()
    print(f'Take {e - s: .3f}')
```
***and got this result:***
```plaintext
Asynchronous: Take 0.011
Synchronous: Take 0.001
```

*why Asynchronous code take longer than Synchronous code ?*
*where I do it wrong ?*

**Comment by Tinche** [comment]
You're not doing anything wrong. What aiofiles does is delegate the file reading operations to a threadpool. This approach is going to be slower than just reading the file directly. The benefit is that while the file is being read in a different thread, your application can do something else in the main thread.

A true, cross-platform way of reading files asynchronously is not available yet, I'm afraid :)

**Comment by jimisola** [comment]
@Tinche Thank you for library

However, we just stumbled into this one with major performance degradation for our application. We didn't want to mix threading and asyncio (the UI, prompt_toolkit, uses asyncio). Have there been any updates to this matter?

If not, it would have been very useful with a note (warning even) on the project's first page that there is a significant difference in performance.
