### ISSUE TITLE
Deprecation on get_event_loop()

### ISSUE THREAD

**Issue by davesteele** [Tinche/aiofiles#129]
I have a report on a test failure due to the deprecation of a get_event_loop() call (https://github.com/davesteele/aiofiles/pull/2). This [patch](https://github.com/davesteele/aiofiles/blob/ea51b5683338d8966fbbcb93f3299e88a3857d70/debian/patches/001-update-get-event-loop.patch) changes the other occurrences of that call.

**Comment by Tinche** [comment]
Don't think that's the right change though. What about get_running_loop?

**Comment by davesteele** [comment]
I'm not the expert here.  Didn't even know the loop policy call existed.

**Comment by davesteele** [comment]
[Outstanding get_event_loop() calls](https://github.com/Tinche/aiofiles/search?q=get_event_loop).

**Comment by davesteele** [comment]
Debian has upgraded Python to 3.11 in prep for the impending [Stable Freeze](https://release.debian.org/bookworm/freeze_policy.html). CI tests are [failing](https://ci.debian.net/packages/a/aiofiles/unstable/amd64/) due to the Deprecation warning, and packages using this code will get the warning.

**Comment by Tinche** [comment]
Thanks for the heads-up, I can replace the calls and do a release soon (in a few days).

**Comment by Tinche** [comment]
Should be fixed on `main`!

**Comment by davesteele** [comment]
Released.
