### ISSUE TITLE
Does aiofiles.write support to write a new line for each message?

### ISSUE THREAD

**Issue by Jack012a** [Tinche/aiofiles#150]
```
async with aiofiles.open('test.txt', mode='w') as f:
        await f.write(msg)
```
What is the best practice to write a new line for each written msg?

Thank you

**Comment by Tinche** [comment]
I'd say the sale as for sync writes:

```
async with aiofiles.open('test.txt', mode='w') as f:
        await f.write(msg + '\n')
```

**Comment by Jack012a** [comment]
I see. Since the msg is very large. I will use the following instead.

[async with aiofiles.open('test.txt', mode='w') as f:
        await f.write(msg + '\n')
        await f.write('\n')](url)

**Comment by Tinche** [comment]
That works too, if you want to avoid a copy of the data.
