### ISSUE TITLE
What is the purpose of binding each file to a particular loop?

### ISSUE THREAD

**Issue by rhelmot** [Tinche/aiofiles#153]
It's somewhat inconvenient that `AsyncBase._loop` exists - it makes it hard to implement a global stdout object via a module-level `stdout = aiofiles.threadpool.wrap(sys.stdout)`. What is the purpose of this attribute? If it is purely for performance reasons, would you accept a PR that changed all references to `self._loop` to `self._loop or asyncio.get_running_loop()`?

**Comment by Tinche** [comment]
I don't remember, it's been a long time.

I wouldn't mind merging a thought-out PR if it solves your problem.
