### ISSUE TITLE
Version compatibility v0.8.0 and v23.1.0

### ISSUE THREAD

**Issue by Hellseher** [Tinche/aiofiles#158]
Hi,

I could not find a release notes or mentioning of so large version jump: 0.8.0 -> 23.1.0.
May you share any mailing list or discussion where it was mentioned and for the package maintainer what could be potential incompatibility.

Thanks.

**Comment by Tinche** [comment]
Hi, we switched the versioning system to CalVer. You can Google around for more info, here's a good article that also goes into why: https://hynek.me/articles/semver-will-not-save-you/

Anyway, the changelog is here: https://github.com/Tinche/aiofiles#2310-2023-02-09

I don't think backwards compatibility was broken however.
