### ISSUE TITLE
creating tests with fake files

### ISSUE THREAD

**Issue by buhman** [Tinche/aiofiles#16]
I noticed aiofiles' unit tests use real file IO.

In my project that uses aiofiles, I think it might make more sense to unit test with faked file IO, using something like [pyfakefs](https://github.com/jmcgeheeiv/pyfakefs).

The setup code I wrote for this feels a little clunky, but it seems to work:

```python
@pytest.fixture
def fs(request):
    """ Fake filesystem. """
    patcher = Patcher()
    patcher.setUp()

    patcher._stubs.SmartSet(threadpool, '_sync_open', patcher.fake_open)

    request.addfinalizer(patcher.tearDown)
    return patcher.fs


@threadpool.wrap.register(FakeFileWrapper)
def _(file, *, loop=None, executor=None):
    return AsyncBufferedIOBase(file, loop=loop, executor=executor)
```

So there are two problems that this code solves:

 - `Patcher` monkey-patches `builtins.open`, but because aiofiles already made a reference to `open`, this doesn't get replaced (contrast to referencing `builtins.open` instead of `_sync_open`)
 - `FakeFileWrapper` from pyfakefs I think probably should be a subclass or registered class of `io.FileIO` or similar.

I am unsure if I should either:

 - directly "fix" these problems in aiofiles and pyfakefs respectively, or
 - make a small pytest plugin that handles this like the code example above.

What do you think?

**Comment by Tinche** [comment]
Well, can you arrange for the monkeypatching to happen before aiofiles is first imported? Also, constantly reaching into `builtins` for `open` is going to have a small performance cost I don't feel is worth it just for easier monkeypatching.

How about a new pull request, rename `_sync_open` in `aiofiles` just `sync_open` and add a paragraph to the README that this can be monkeypatched in tests?

**Comment by buhman** [comment]
> Well, can you arrange for the monkeypatching to happen before aiofiles is first imported?

While this is possible, it is probably uglier.

> How about a new pull request, rename _sync_open in aiofiles just sync_open and add a paragraph to the README that this can be monkeypatched in tests?

I like this more.

**Comment by buhman** [comment]
@Tinche how does #19 look?

**Comment by buhman** [comment]
#19 is merged.
