### ISSUE TITLE
No implementation of cwd or abspath?

### ISSUE THREAD

**Issue by GodefroyClair** [Tinche/aiofiles#181]
If I'm not mistaken, neither`get_cwd` nor `abspath` (which is juste `normpath(join(os.getcwd(), path))` according to the [doc  in the os package](https://docs.python.org/3/library/os.path.html#os.path.abspath)) are implemented in aiofiles.
It seems like important function that do IO operations if I'm not mistaken. Is there a fundamental reason why it is not implemented in aiofiles?
Thanks!

**Comment by Tinche** [comment]
There's no fundamental reason. Are `get_cwd` and `abspath` blocking in the first place?

Probably no one asked for it or contributed it. If you feel like adding it (should be fairly simple) feel free to send a PR!

**Comment by GodefroyClair** [comment]
Well, `abspath` calls `getcwd` and, on Linux,`getcwd`calls the POSIX functon `getcwd`. This function is a __system call__.
Exactly what implementation is behind that is beyond my knowledge. How would you evaluate how "blocking" a function is ?
https://hg.python.org/cpython/file/tip/Modules/posixmodule.c
https://man7.org/linux/man-pages/man3/getcwd.3.html

...and yes, if needed, I would be very happy to help and send a PR...
