### ISSUE TITLE
AttributeError("module 'aiofiles' has no attribute 'tempfile'")

### ISSUE THREAD

**Issue by RomanPerekhrest** [Tinche/aiofiles#186]
Got `AttributeError("module 'aiofiles' has no attribute 'tempfile'")` on line:
`async with aiofiles.tempfile.TemporaryFile('w') as f:`.

Python version: `3.10.12`
OS: Ubuntu 22

**Comment by Tinche** [comment]
Which version of aiofiles are you using? You can check with `pip list`.

**Comment by Tinche** [comment]
Oh that's pretty ancient. The `tempfile` thing was added in 0.7. You'll need to upgrade.

**Comment by lmaddox** [comment]
thank you. `pip install -U aiofiles` fixed it for me.
