### ISSUE TITLE
pickle support

### ISSUE THREAD

**Issue by ayharano** [Tinche/aiofiles#21]
Similar to issue #20 , how can standard [pickle](https://docs.python.org/3/library/pickle.html) interface be used along with aiofiles? How could it be done? By mimicking pickle sourcecode equivalent into aiofiles? Can such support be a feature of aiofiles?

**Comment by gwerbin** [comment]
Couldn't you just use `pickle.dumps(...)` followed by `aiofiles.open(..., 'wb')`?

**Comment by ayharano** [comment]
I didn't understand your proposition.Could you post an example to illustrate?

**Comment by yeraydiazdiaz** [comment]
I believe @gwerbin means doing something like this:

```
import asyncio
import os
import pickle
import aiofiles

class Foo:
    def __init__(self, bar):
        self.bar = bar


async def pickler(obj):
    async with aiofiles.open('foo.pickle', 'wb') as f:
        pickled_foo = pickle.dumps(obj)
        await f.write(pickled_foo)

async def unpickler():
    async with aiofiles.open('foo.pickle', 'rb') as f:
        pickled_foo  = await f.read()

    return pickle.loads(pickled_foo)

async def main():
    my_foo = Foo('baz')
    await pickler(my_foo)
    assert os.stat('foo.pickle').st_size > 0
    unpickled_foo = await unpickler()
    assert unpickled_foo.bar == my_foo.bar

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by gwerbin** [comment]
@yeraydiazdiaz yes, thank you :) Forgot about this one.

**Comment by tomchristie** [comment]
Would suggest closing this issue. 😄

**Comment by Tinche** [comment]
Agreed, serialization formats should be a different layer than aiofiles.

**Comment by zoltan-fedor** [comment]
The read back from file doesn't work if the file had two separate objects pickled into.
