### ISSUE TITLE
`async with` throws error

### ISSUE THREAD

**Issue by ek-nath** [Tinche/aiofiles#38]
<pre><code>import aiofiles
print(aiofiles.__version__)

async with aiofiles.open('wctDA2.tmp', mode='r') as f:
    contents = await f.read()
print(contents)
</code></pre>

Output:
<pre><code>
File "a.py", line 4
    async with aiofiles.open('wctDA2.tmp', mode='r') as f:
             ^
SyntaxError: invalid syntax
</code></pre>

Details:

1. python: Python 3.6.4 :: Anaconda custom (64-bit)
2. OS: Windows 10 x64
3. aiofiles: 0.3.2

**Comment by Dobatymo** [comment]
You can only have "async with" within "async def".

**Comment by ek-nath** [comment]
That's just dumb of me. Sorry and thank you.
