### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by Modelmat** [Tinche/aiofiles#42]
Are there any known issues running in python 3.7?

**Comment by iiSeymour** [comment]
Yes see my branch [here](https://github.com/iiSeymour/aiofiles/commits/py37-tests). In short 

- Travis CI doesn't yet have python 3.7 *(release)* build.
- `asyncio.async` has been removed.
- `__aiter__` must return an asynchronous iterator object.
- Compatibility issues with `pytest-asyncio`

It appears to be difficult to support Python 3.3, 3.4 and Python 3.7. I don't how @Tinche feels about having Python 3.5 as the minimal supported version?

**Comment by Tinche** [comment]
Honestly I'd be ok with going 3.5+.

**Comment by iiSeymour** [comment]
Great, I've opened #43.
