### ISSUE TITLE
Package cannot be installed via `pip --no-binaries`

### ISSUE THREAD

**Issue by podshumok** [Tinche/aiofiles#6]
I prefer to not install binary packages like wheels for libraries, that do not require compilation during installation.
But there is no .gz package in PIPI, so `pip install --no-binaries :all: aiofiles` will fail.

**Comment by Tinche** [comment]
Yeah, I was hoping just a wheel would be enough :)

I'll put up a sdist for you over the weekend.

**Comment by Tinche** [comment]
This should work now, please close if it does.

**Comment by podshumok** [comment]
yep, thanks
