### ISSUE TITLE
Update pip package.

### ISSUE THREAD

**Issue by NotoriousRebel** [Tinche/aiofiles#67]
I just pip installed the package and attempted to do ```aiofiles.os.mkdir```
and it crashed because that function didn't exist. After debugging it appears that the pip package is missing mkdir inside os.py.  Please update the pip package.

**Comment by blueyed** [comment]
Duplicate of https://github.com/Tinche/aiofiles/issues/65 - please close it.

**Comment by NotoriousRebel** [comment]
@blueyed Ah apologies I just reread the issues thanks for pointing tihs out!
