### ISSUE TITLE
DeprecationWarning at aiofiles.os:8

### ISSUE THREAD

**Issue by HacKanCuBa** [Tinche/aiofiles#74]
Hi there! Pytest is *correctly* complaining about the use of `@coroutine` decorator at aiofiles.os line 8. This is for the current latest 0.5.0 version.

https://github.com/Tinche/aiofiles/blob/258e95640d6242c53a1c0d84e68343d79d80d781/aiofiles/os.py#L7-L16

The fix would be to use `async def` directly:

```python
def wrap(func):
    @wraps(func)
    async def run(*args, loop=None, executor=None, **kwargs):
        if loop is None:
            loop = asyncio.get_event_loop()
        pfunc = partial(func, *args, **kwargs)
        return loop.run_in_executor(executor, pfunc)

    return run
```

**Comment by Tinche** [comment]
Agreed, could you create a quick PR?

**Comment by gyermolenko** [comment]
> Agreed, could you create a quick PR?

related #54

**Comment by HacKanCuBa** [comment]
> Agreed, could you create a quick PR?

Sure, give me 5' :)

**Comment by HacKanCuBa** [comment]
Done in #75

**Comment by HacKanCuBa** [comment]
> > Agreed, could you create a quick PR?
> 
> related #54 (! please note that it also changes return type of the wrapped func)

Woops, sorry I missed this. Both PRs clashes, so I guess we need to pick one.

**Comment by HacKanCuBa** [comment]
I saw that Travis failed in my PR so I checked out the project locally and see that, at least for py3.8, tests are failing for what is mentioned in #54

**Comment by Tinche** [comment]
Merged that one in! Can this issue now be closed?

**Comment by HacKanCuBa** [comment]
Sure do! I'm closing it. Thanks!
