### ISSUE TITLE
aiofile Corrupts images

### ISSUE THREAD

**Issue by oguh43** [Tinche/aiofiles#78]
It seems like aiofile doesnt support writing bytes, or respect this line: `async with aiofile.AIOFile(temp,"wb") as f:`

**Comment by Tinche** [comment]
Could you prepare a minimal example?

**Comment by oguh43** [comment]
above line produces https://anonfiles.com/V2YfS1B7o8/img_ZIP , while aiofiles works just fine.

**Comment by Tinche** [comment]
aiofile is a different library (by a different author), so create a bug there please :)

**Comment by oguh43** [comment]
I am so sorry, didnt realize this :D
