### ISSUE TITLE
DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead

### ISSUE THREAD

**Issue by timkofu** [Tinche/aiofiles#84]
I'm getting the exception below on Python 3.8:
```
...lib/python3.8/site-packages/aiofiles/os.py:10: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def run(*args, loop=None, executor=None, **kwargs):
```

```
In [2]: aiofiles.__version__
Out[2]: '0.5.0'
```

**Comment by shan-guo** [comment]
> I'm getting the exception below on Python 3.8:
> 
> ```
> ...lib/python3.8/site-packages/aiofiles/os.py:10: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
>     def run(*args, loop=None, executor=None, **kwargs):
> ```
> 
> ```
> In [2]: aiofiles.__version__
> Out[2]: '0.5.0'
> ```

So did I, Have you solved it now ?

**Comment by StigKorsnes** [comment]
If you have look at the commit for os.py, you will se those exact changes. V 0.6 just not released.

**Comment by samuelcolvin** [comment]
v0.6 is released!

This can be closed.
