### ISSUE TITLE
about code generator

### ISSUE THREAD

**Issue by GoddessLuBoYan** [Tinche/aiofiles#99]
your idea is so good(use executor to run async task)
however, anyone can not list all the functions.
so, what if use a code generator to generate all the api

**Comment by Tinche** [comment]
Not sure what exactly you're suggesting, generating docs or the async wrappers differently?

**Comment by GoddessLuBoYan** [comment]
emmm, I mean, there's so many functions in module 'os', 'tempfile', etc.
however, it's difficult to copy all the functions into your package.
you see, now there's many issues that want to add built-in function support

so, if you can generate all the functions to async mode
or, if you can public the normal async-wrap
the package will be more univeral

**Comment by Tinche** [comment]
Thanks for the suggestion, I'll consider it.
